version: '3'
services:
  rwdb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: ashop
      # MYSQL_DATABASE: realworld

    ports:
      - 3306:3306
    volumes:
      - "~/learnDir/data/mysql:/var/lib/mysql"