server:
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
    # reflection: true
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123@tcp(139.9.0.138:3306)/ashop?charset=utf8mb4&parseTime=True&loc=Local
    # source: root:123@tcp(127.0.0.1:3306)/ashop?charset=utf8mb4&parseTime=True&loc=Local

  redis:
    addr: 139.9.0.138:6379
    # addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
