// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: v1/idgen.proto

package v1

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenIDReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GenIDReply) Reset() {
	*x = GenIDReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_idgen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenIDReply) ProtoMessage() {}

func (x *GenIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_idgen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenIDReply.ProtoReflect.Descriptor instead.
func (*GenIDReply) Descriptor() ([]byte, []int) {
	return file_v1_idgen_proto_rawDescGZIP(), []int{0}
}

func (x *GenIDReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GenIDsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GenIDsReq) Reset() {
	*x = GenIDsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_idgen_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenIDsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenIDsReq) ProtoMessage() {}

func (x *GenIDsReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_idgen_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenIDsReq.ProtoReflect.Descriptor instead.
func (*GenIDsReq) Descriptor() ([]byte, []int) {
	return file_v1_idgen_proto_rawDescGZIP(), []int{1}
}

func (x *GenIDsReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GenIDsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *GenIDsReply) Reset() {
	*x = GenIDsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_idgen_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenIDsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenIDsReply) ProtoMessage() {}

func (x *GenIDsReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_idgen_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenIDsReply.ProtoReflect.Descriptor instead.
func (*GenIDsReply) Descriptor() ([]byte, []int) {
	return file_v1_idgen_proto_rawDescGZIP(), []int{2}
}

func (x *GenIDsReply) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_v1_idgen_proto protoreflect.FileDescriptor

var file_v1_idgen_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x76, 0x31, 0x2f, 0x69, 0x64, 0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x10, 0x69, 0x64, 0x67, 0x65, 0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1c, 0x0a,
	0x0a, 0x47, 0x65, 0x6e, 0x49, 0x44, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x21, 0x0a, 0x09, 0x47,
	0x65, 0x6e, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x1f,
	0x0a, 0x0b, 0x47, 0x65, 0x6e, 0x49, 0x44, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x69, 0x64, 0x73, 0x32,
	0x9a, 0x01, 0x0a, 0x05, 0x49, 0x64, 0x47, 0x65, 0x6e, 0x12, 0x44, 0x0a, 0x0a, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x44, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x1c, 0x2e, 0x69, 0x64, 0x67, 0x65, 0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x6e, 0x49, 0x44, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12,
	0x4b, 0x0a, 0x0b, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x44, 0x73, 0x12, 0x1b,
	0x2e, 0x69, 0x64, 0x67, 0x65, 0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x6e, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x69, 0x64,
	0x67, 0x65, 0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x6e, 0x49, 0x44, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x19, 0x5a, 0x17,
	0x61, 0x70, 0x69, 0x2f, 0x69, 0x64, 0x67, 0x65, 0x6e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_idgen_proto_rawDescOnce sync.Once
	file_v1_idgen_proto_rawDescData = file_v1_idgen_proto_rawDesc
)

func file_v1_idgen_proto_rawDescGZIP() []byte {
	file_v1_idgen_proto_rawDescOnce.Do(func() {
		file_v1_idgen_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_idgen_proto_rawDescData)
	})
	return file_v1_idgen_proto_rawDescData
}

var file_v1_idgen_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_idgen_proto_goTypes = []interface{}{
	(*GenIDReply)(nil),  // 0: idgen.service.v1.GenIDReply
	(*GenIDsReq)(nil),   // 1: idgen.service.v1.GenIDsReq
	(*GenIDsReply)(nil), // 2: idgen.service.v1.GenIDsReply
	(*empty.Empty)(nil), // 3: google.protobuf.Empty
}
var file_v1_idgen_proto_depIdxs = []int32{
	3, // 0: idgen.service.v1.IdGen.GenerateID:input_type -> google.protobuf.Empty
	1, // 1: idgen.service.v1.IdGen.GenerateIDs:input_type -> idgen.service.v1.GenIDsReq
	0, // 2: idgen.service.v1.IdGen.GenerateID:output_type -> idgen.service.v1.GenIDReply
	2, // 3: idgen.service.v1.IdGen.GenerateIDs:output_type -> idgen.service.v1.GenIDsReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_idgen_proto_init() }
func file_v1_idgen_proto_init() {
	if File_v1_idgen_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_idgen_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenIDReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_idgen_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenIDsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_idgen_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenIDsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_idgen_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_idgen_proto_goTypes,
		DependencyIndexes: file_v1_idgen_proto_depIdxs,
		MessageInfos:      file_v1_idgen_proto_msgTypes,
	}.Build()
	File_v1_idgen_proto = out.File
	file_v1_idgen_proto_rawDesc = nil
	file_v1_idgen_proto_goTypes = nil
	file_v1_idgen_proto_depIdxs = nil
}
