// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ashop/app/idgen/service/internal/biz"
	"ashop/app/idgen/service/internal/conf"
	"ashop/app/idgen/service/internal/server"
	"ashop/app/idgen/service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, node *conf.Node, logger log.Logger) (*kratos.App, func(), error) {
	snowflakeNode := biz.InitSnowflake(node)
	idGenUsecase := biz.NewIdGenUsecase(logger, snowflakeNode)
	idGenService := service.NewIdGenService(idGenUsecase)
	grpcServer := server.NewGRPCServer(confServer, idGenService, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
	}, nil
}
