apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  selector:
    app: user
  ports:
    - name: port-http
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: port-grpc
      protocol: TCP
      port: 9000
      targetPort: 9000
